### ISSUE TITLE
需要新增邊界在每一天之間

### ISSUE THREAD

**Issue by PinkNekoFist** [PinkNekoFist/personal-note#3]
![圖片](https://github.com/user-attachments/assets/b627018e-ddc5-467e-b37c-189c7e0907ec)

如圖，不太能區分每一天，有點太白了，加個簡單的邊界應該可以有效的改善
@tianlong0527

**Comment by tianlong0527** [comment]
邊框要再去設計，windows form內建的邊框只有兩個，都很醜

更：
![image](https://github.com/user-attachments/assets/a21da3b9-cc8a-4b77-970a-c85f06d563b8)
好像還行
